### ISSUE TITLE
[ng-fullstack] Cannot serve on host 0.0.0.0

### ISSUE THREAD

**Issue by quytoanvu** [ericmdantas/aliv#19]
Hi team, 

I launched web server using file `.alivrc` with the following content:

```
{
    "quiet": false,
    "host": "0.0.0.0",
    "port": 3000,
    "secure": true,
    "pathIndex": "client/dev",
    "only": "client/dev/**/*",
    "proxy": true,
    "proxyWhen": "/api/path/to/proxy/*",
    "proxyTarget": "http://proxy-to-my-target:8080"
}
```

and I cannot connect to the web server. Sound like it didn't get the host value to launch the server.

Thank you,
Toan Vu

**Comment by ericmdantas** [comment]
Sounds like a bug.

Any reasons why you're not using "127.0.0.1"?

**Comment by ericmdantas** [comment]
ping

**Comment by ericmdantas** [comment]
Closing due to no response.
