### ISSUE TITLE
Add "timeout" feature

### ISSUE THREAD

**Issue by only-cliches** [ericmdantas/aliv#28]
Been using this lib for a development server of a new project.  Excellent work, thank you for having something simple, straightforward and powerful.

I have a suggested feature I'd like to see.  Instead of reloading instantly on the first file change, setup a timeout that allows additional files to be affected before the reload.  

This could be a simple "timeout" option added to the config, setting it to "100" would cause the server to wait 100 ms before sending a refresh after a file has changed.

This has come up as a problem quite a few times in my use case.  I've got webpack watching for changes on typescript files to compile to js, then node-sass listening for changes to the sass files and compiling to CSS.  Quite a few times I'll change CSS & TS files in the same save cycle, then when the server refreshes either the JS or CSS is a cycle behind (depending on which one compiled faster).

**Comment by ericmdantas** [comment]
Hey there, @ClickSimply. I'm glad the project is achieving its goals :smile: 

Thanks for the suggestion, it should be easy enough to get it done fast. It'll be released in `1.7`.

As for the new option, what do you think of the name `--reloadDelay` and `--rd`?

**Comment by only-cliches** [comment]
`--reloadDelay` would be perfect!  Thank  you. :D

**Comment by ericmdantas** [comment]
Closed by 9f67775

**Comment by ericmdantas** [comment]
`1.7.0` released. Please, give it a try :smile:

**Comment by only-cliches** [comment]
Hey dude, thanks for getting this update out so fast!   Testing this out the past few days it's working great, much appreciated.

**Comment by ericmdantas** [comment]
:+1:
