### ISSUE TITLE
http -> https redirection

### ISSUE THREAD

**Issue by Shuunen** [ericmdantas/aliv#35]
hi again :)

it would be great to redirect http to https when aliv is started in secure mode,

actually http is just not accessible.

I also tried with this conf : 
```
{
	"quiet": false,
        "root": "dist/",
	"port": 3000,
	"host": "foobar.io",
	"secure": true,
	"proxy": true,
	"proxyWhen": "/^http:/",
	"proxyTarget": "https://foobar.io:3000"
}
```

**Comment by ericmdantas** [comment]
Hey!

Yeah, redirection is not handled right now and it can catch the user by surprised. Thanks for reminding me.

**Comment by Shuunen** [comment]
No prob :) i'm just trying to have my PWA working locally :)

**Comment by Shuunen** [comment]
I opened : https://github.com/ericmdantas/aliv/pull/36

**Comment by ericmdantas** [comment]
`v1.9.0` released.
