### ISSUE TITLE
HTTP2 doesn't work?

### ISSUE THREAD

**Issue by MicahZoltu** [ericmdantas/aliv#41]
```
npm install aliv
npx aliv --port 8081 --http2 --noBrowser --root output
```
Trying to navigate to `http://127.0.0.1:8081` from Firefox results in:
```
The connection was reset
```
Trying to navigate to `http://127.0.0.1:8081` from from Chrome results in:
```
This page isn’t working
127.0.0.1 didn’t send any data.
ERR_EMPTY_RESPONSE
```

If I remove the `--http2`, everything works as expected.

Node Version: v10.15.0
aliv Version: 1.11.4

**Comment by ericmdantas** [comment]
Hey, @MicahZoltu.

Shouldn't you try to navigate to `https://` instead of `http://`? We do have an issue when trying to use node 11.1 and above, but versions 10.x should be working just fine - I just tested on my Windows machine and it seems to be working alright.

Just to make it clear, when you choose to work with `http2`, it'll force you on `https` and when the flag `--http2` is omitted, `http` is used by default.

**Comment by MicahZoltu** [comment]
That was the problem, thanks!  A quick perusal of the internet suggests that HTTP/2 should work over both HTTP and HTTPS.  Is there a reason that the `--http2` flag _also_ enables `https`?

**Comment by ericmdantas** [comment]
It's been a while, but last time I checked HTTP/2 was supposed to work over secured connections. There might be some workarounds, but those seem to be the exception of the rule.

I remember Golang even went a step further and made every `https` server a `http2` server when `go 1.8` came out.

**Comment by MicahZoltu** [comment]
It seems that HTTP/2 spec doesn't require HTTPS, it is designed to work over HTTPS or HTTP, but all major browsers supposedly refuse to speak HTTP/2 over HTTP.  I'm guessing their thought is that for a production system, there is no reason to _not_ use HTTPS and they saw this as an opportunity to enforce that.

For a test server though, often times testing without TLS is convenient as you don't get browser security warnings like you do when connecting to an SSL server.  I'm not sure if this library is designed to be a production HTTP/2 server or a dev server, but that may inform the final decision.

I will admit, the opportunity to do testing against an HTTP HTTP/2 server is limited when most browsers won't connect.  :/

**Comment by ericmdantas** [comment]
> It seems that HTTP/2 spec doesn't require HTTPS, it is designed to work over HTTPS or HTTP, but all major browsers supposedly refuse to speak HTTP/2 over HTTP.

Yeah, it seemed like it was just what they needed to force everybody to have a secure connection - be that good or bad. No wonder why language maintainers didn't even bother to add the option to have some workarounds.

> I'm not sure if this library is designed to be a production HTTP/2 server or a dev server

Definitely dev server - it should work in prod too, but it wasn't created with that in mind.

> I will admit, the opportunity to do testing against an HTTP HTTP/2 server is limited when most browsers won't connect. :/

Right?

But hey, if that changes in the future, I'll gladly make the change :+1:
